"""Rendering the preview card.

The card is the safety mechanism of the whole capture flow: nothing reaches the
vault until someone reads this and taps `Save`. So it has to show the things a
person would regret not seeing — **where it will be written** above all, then
the title, the tags, and an honest note of anything the pipeline could not do.

Two rendering rules, both learned in earlier phases:

* every literal goes through the escaper, because `Q1 2026 — costs (draft)` is
  a perfectly ordinary title and a 400 from the Bot API rejects the *message*,
  not the character;
* the body is an excerpt, not the note. A transcription of a dense page can be
  twenty thousand characters, and a preview that had to be paged would stop
  being a preview.
"""

from __future__ import annotations

from telegram import InlineKeyboardMarkup

from discoverygram.app.capture import Resolution
from discoverygram.app.ingest import Draft
from discoverygram.bot.render import button_grid, keyboard
from discoverygram.bot.render import escape_markdown_v2 as esc
from discoverygram.bot.tokens import CallbackTokens

DRAFT_ACTION = "dr"

# How much of the body the card shows. Enough to recognise the note and to
# catch a transcription that went wrong, short enough to stay one message.
PREVIEW_CHARS = 900

UNTITLED = "(no title)"


def render_draft(draft: Draft) -> str:
    """The preview card, as MarkdownV2."""
    lines = [f"*{esc('Draft')}*", ""]

    title = draft.title.strip() or UNTITLED
    lines.append(f"*{esc('Title:')}* {esc(title)}")
    lines.append(f"*{esc('Path:')}* `{_code(draft.path or '(not resolved)')}`")

    if draft.tags:
        lines.append(f"*{esc('Tags:')}* {esc(' '.join('#' + tag for tag in draft.tags))}")
    if draft.attachments:
        count = len(draft.attachments)
        lines.append(f"*{esc('Attached:')}* {esc(f'{count} file' + ('s' if count != 1 else ''))}")

    body = _excerpt(draft.body)
    if body:
        lines += ["", esc(body)]
    else:
        lines += ["", esc("(no body text)")]

    if draft.summary:
        lines += ["", f"*{esc('Summary:')}* {esc(draft.summary)}"]

    if draft.provenance is not None and (draft.provenance.provider or draft.provenance.model):
        origin = f"{draft.provenance.provider}/{draft.provenance.model}".strip("/")
        lines += ["", esc(f"Generated by {origin}.")]

    for warning in draft.warnings:
        lines.append("⚠️ " + esc(warning))

    lines += ["", esc("Nothing is written until you tap Save.")]
    return "\n".join(lines)


def draft_keyboard(token: str) -> InlineKeyboardMarkup:
    """The five buttons the roadmap named, all against one token.

    One token per *draft*, not per button: the draft is one piece of state and
    every button acts on the same one, so paging back and forth through a
    capture costs a single session entry.
    """
    return keyboard(
        [
            [("💾 Save", CallbackTokens.with_args(token, "save"))],
            [
                ("✏️ Title", CallbackTokens.with_args(token, "title")),
                ("📁 Path", CallbackTokens.with_args(token, "path")),
            ],
            [
                ("🔄 Regenerate", CallbackTokens.with_args(token, "regen")),
                ("✖ Cancel", CallbackTokens.with_args(token, "cancel")),
            ],
        ]
    )


def render_ambiguity(target: str, resolution: Resolution) -> str:
    """Asked when a name matches more than one folder.

    Only ever shown for genuine ambiguity: a keyboard offering one choice is
    friction pretending to be safety.
    """
    return f"{esc(f'More than one folder is called “{target}”. Which one?')}\n\n" + "\n".join(
        f"• `{_code(path)}`" for path in resolution.candidates
    )


def ambiguity_keyboard(token: str, candidates: tuple[str, ...]) -> InlineKeyboardMarkup:
    """One button per candidate, addressed by index against the draft's token."""
    buttons = [
        (_shorten(path), CallbackTokens.with_args(token, "pick", index))
        for index, path in enumerate(candidates)
    ]
    rows = button_grid(buttons, columns=1)
    rows.append([("✖ Cancel", CallbackTokens.with_args(token, "cancel"))])
    return keyboard(rows)


def render_saved(path: str, *, renamed_from: str = "") -> str:
    """Confirmation, naming the collision rule when it fired.

    A silently renamed note is a note the user will look for in the wrong
    place, so the rename is stated rather than hidden.
    """
    lines = [f"{esc('Saved to')} `{_code(path)}`{esc('.')}"]
    if renamed_from:
        lines.append(
            esc(
                f"{renamed_from} already existed, so I saved this alongside it rather than "
                f"overwriting it."
            )
        )
    return "\n".join(lines)


def render_answer(text: str, sources: tuple[str, ...]) -> str:
    """An `/ask` answer with its citations listed under it."""
    lines = [esc(text)]
    if sources:
        lines += ["", f"*{esc('Sources')}*"]
        lines += [f"• `{_code(path)}`" for path in sources]
    return "\n".join(lines)


def _excerpt(body: str) -> str:
    text = body.strip()
    if len(text) <= PREVIEW_CHARS:
        return text
    return text[:PREVIEW_CHARS].rstrip() + " […]"


def _code(value: str) -> str:
    """Inside a code span only a backtick needs handling, and it cannot be escaped."""
    return value.replace("`", "")


def _shorten(path: str, limit: int = 40) -> str:
    """A path short enough for a button label, keeping the end that identifies it."""
    if len(path) <= limit:
        return path
    return "…" + path[-(limit - 1) :]


__all__ = [
    "DRAFT_ACTION",
    "PREVIEW_CHARS",
    "ambiguity_keyboard",
    "draft_keyboard",
    "render_ambiguity",
    "render_answer",
    "render_draft",
    "render_saved",
]
